print(" \nOké de volgende dag ga je naar het contact wat je hebt gekregen van je smokkelaar. \nHij zet dat hij toevallig nog 4 plaatsen over en hoorde dat wij interesse had dus we kunnen nu instappen.")
print(" \nHij gaat naar een land genaamd Nederland, je hebt nog nooit van dit land gehoord maar hij zegt dat je daar een goed nieuw begin kan starten. ")
print(" \nNa een reis van een week in een vrachtwagen kom je aan in Rotterdam waar je wordt geadviseerd om naar het politiebureau te gaan om je te laten registreren in dit land.")
print(" \nDit doe je ook en na wat papieren kom je in een azc met allemaal aardige mensen en medewerkers")
print("")
print("███████╗██╗███╗░░██╗██████╗░███████╗  ░░███╗░░")
print("██╔════╝██║████╗░██║██╔══██╗██╔════╝  ░████║░░")
print("█████╗░░██║██╔██╗██║██║░░██║█████╗░░  ██╔██║░░")
print("██╔══╝░░██║██║╚████║██║░░██║██╔══╝░░  ╚═╝██║░░")
print("███████╗██║██║░╚███║██████╔╝███████╗  ███████╗")
print("╚══════╝╚═╝╚═╝░░╚══╝╚═════╝░╚══════╝  ╚══════╝")
print("")
print("Dit is einde 1 de reis zonder te veel problemen :) bedankt voor het spelen")
